// Golden vector generator for the GF(2^8) RTL core.
//
// The GF functions below are copied VERBATIM from ref/isro_has_main.cpp
// (lines 16-62) so that the vectors this emits are produced by exactly the
// code the RTL is claimed to match. Do not "clean up" or retype them.
//
// Build: g++ -O2 -o gen_golden gen_golden.cpp
// Run:   ./gen_golden          (writes golden/*.hex next to the cwd)

#include <cstdint>
#include <iostream>
#include <fstream>
#include <iomanip>

using namespace std;

// ===== BEGIN verbatim copy from ref/isro_has_main.cpp =====

int gf_exp[512];
int gf_log[256];

void init_gf() {
    int x = 1;

    for(int i=0;i<255;i++) {
        gf_exp[i] = x;
        gf_log[x] = i;

        x <<= 1;

        if(x & 0x100)
            x ^= 0x11D;
    }

    for(int i=255;i<512;i++)
        gf_exp[i] = gf_exp[i-255];

    gf_log[0] = -1;
}

uint8_t gf_add(uint8_t a, uint8_t b) {
    return a ^ b;
}

uint8_t gf_mul(uint8_t a, uint8_t b) {

    if(a == 0 || b == 0)
        return 0;

    return gf_exp[gf_log[a] + gf_log[b]];
}

// gf_inv is NOT copied verbatim: the reference calls exit(1) on a==0, which
// would abort this generator. The a!=0 path is identical; a==0 is emitted as
// the error case instead, which is what the RTL's err flag must reproduce.

uint8_t gf_inv_nonzero(uint8_t a) {
    return gf_exp[255 - gf_log[a]];
}

// ===== END verbatim copy =====

static ofstream open_or_die(const char *path) {
    ofstream f(path);
    if(!f.is_open()) {
        cerr << "Cannot open " << path << " for writing!" << endl;
        exit(1);
    }
    return f;
}

static string hex2(int v) {
    static const char *d = "0123456789ABCDEF";
    string s;
    s += d[(v >> 4) & 0xF];
    s += d[v & 0xF];
    return s;
}

int main() {

    init_gf();

    // ---- ROM contents: exp[0..511] and log[0..255] -------------------
    // These let the RTL instantiate the SAME tables the C++ built, rather
    // than tables regenerated by an independent (possibly 0x11B) source.

    {
        ofstream f = open_or_die("golden/gf_exp.hex");
        for(int i=0;i<512;i++)
            f << hex2(gf_exp[i]) << "\n";
    }

    {
        // gf_log[0] is -1 in the C++ (a sentinel, never indexed because
        // gf_mul short-circuits on zero). Emit 00 for it; the RTL must
        // likewise never use the log of zero on a live path.
        ofstream f = open_or_die("golden/gf_log.hex");
        for(int i=0;i<256;i++)
            f << hex2(i == 0 ? 0 : gf_log[i]) << "\n";
    }

    // ---- Exhaustive multiply: all 65,536 ordered pairs ---------------
    // Emitted b-fastest so the testbench walks it with two nested loops.
    //
    // One value per line, in three PARALLEL files rather than "aa bb pp"
    // triples on one line: $readmemh splits on whitespace, so a three-token
    // line loads as three separate array entries, not one packed word.
    // (Verified against ModelSim before relying on it.) The testbench
    // indexes the three arrays in step.

    {
        ofstream fa = open_or_die("golden/gf_mul_a.hex");
        ofstream fb = open_or_die("golden/gf_mul_b.hex");
        ofstream fp = open_or_die("golden/gf_mul_p.hex");
        long count = 0;
        for(int a=0;a<256;a++) {
            for(int b=0;b<256;b++) {
                fa << hex2(a) << "\n";
                fb << hex2(b) << "\n";
                fp << hex2(gf_mul((uint8_t)a, (uint8_t)b)) << "\n";
                count++;
            }
        }
        cerr << "gf_mul_{a,b,p}.hex:  " << count << " vectors" << endl;
    }

    // ---- Exhaustive inverse: all 256 inputs ---------------------------
    // Parallel files again: a, inv(a), and the expected error flag.
    // a == 0 is the fatal case in the C++ (it calls exit(1)); the RTL must
    // raise err there and the inverse value is don't-care, emitted as 00.

    {
        ofstream fa = open_or_die("golden/gf_inv_a.hex");
        ofstream fi = open_or_die("golden/gf_inv_i.hex");
        ofstream fe = open_or_die("golden/gf_inv_e.hex");
        for(int a=0;a<256;a++) {
            fa << hex2(a) << "\n";
            if(a == 0) {
                fi << hex2(0) << "\n";
                fe << hex2(1) << "\n";
            } else {
                fi << hex2(gf_inv_nonzero((uint8_t)a)) << "\n";
                fe << hex2(0) << "\n";
            }
        }
        cerr << "gf_inv_{a,i,e}.hex:  256 vectors" << endl;
    }

    // ---- Self-check on the generator itself ---------------------------
    // Guards against a silently wrong table: verify the field axioms hold
    // for the vectors we just emitted. If the polynomial were 0x11B, or the
    // tables mis-built, these fail here rather than in the RTL.

    int fails = 0;

    // alpha = 2 is the generator: exp[1] must be 2.
    if(gf_exp[1] != 2) { cerr << "FAIL: generator is not alpha=2" << endl; fails++; }

    // The primitive polynomial is 0x11D, so alpha^8 = 0x1D.
    if(gf_exp[8] != 0x1D) {
        cerr << "FAIL: alpha^8 = 0x" << hex << gf_exp[8]
             << " (expected 0x1D for poly 0x11D; 0x1B means 0x11B was used)"
             << dec << endl;
        fails++;
    }

    // exp has order exactly 255.
    if(gf_exp[255] != 1) { cerr << "FAIL: alpha^255 != 1" << endl; fails++; }

    for(int a=1;a<256;a++) {

        // a * a^-1 == 1 for every nonzero a
        if(gf_mul((uint8_t)a, gf_inv_nonzero((uint8_t)a)) != 1) {
            cerr << "FAIL: a * inv(a) != 1 at a=" << a << endl;
            fails++;
        }

        // 1 is the multiplicative identity
        if(gf_mul((uint8_t)a, 1) != a) {
            cerr << "FAIL: a * 1 != a at a=" << a << endl;
            fails++;
        }

        // log/exp round-trip
        if(gf_exp[gf_log[a]] != a) {
            cerr << "FAIL: exp(log(a)) != a at a=" << a << endl;
            fails++;
        }
    }

    for(int a=0;a<256;a++) {

        // zero annihilates
        if(gf_mul((uint8_t)a, 0) != 0 || gf_mul(0, (uint8_t)a) != 0) {
            cerr << "FAIL: zero product at a=" << a << endl;
            fails++;
        }

        for(int b=0;b<256;b++) {
            // commutativity
            if(gf_mul((uint8_t)a,(uint8_t)b) != gf_mul((uint8_t)b,(uint8_t)a)) {
                cerr << "FAIL: not commutative at " << a << "," << b << endl;
                fails++;
            }
        }
    }

    if(fails) {
        cerr << "\nGENERATOR SELF-CHECK FAILED (" << fails << " errors)."
             << " Vectors are NOT trustworthy." << endl;
        return 1;
    }

    cerr << "\nGenerator self-check passed."
         << " alpha^8 = 0x1D confirms polynomial 0x11D." << endl;
    return 0;
}
